### ISSUE TITLE
laravel 5.2 compatiblity

### ISSUE THREAD

**Issue by imami** [Vinelab/NeoEloquent#141]
Isn't NeoEloquent compatible with Laravel 5.2 yet?

**Comment by AzeemMichael** [comment]
Yep, I'm getting "Call to undefined method Illuminate\Foundation\Application::bindShared() in /Users/amichael/www/laravel-projects/singlet/vendor/vinelab/neoeloquent/src/Vinelab/NeoEloquent/MigrationServiceProvider.php on line 50". Application:: bindShared() has been renamed to Application:: singleton(). I tried renaming all references to it. But, then got "Class Illuminate\Foundation\Composer does not exist".

**Comment by bramdevries** [comment]
Changed the calls to `bindShared` to `singleton` manually, but now getting the following:

```php
Call to a member function processSelect() on null in /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 1403
```

**Comment by AzeemMichael** [comment]
Looks like there is already a pull request with a fix for deprecated function bindShared()

**Comment by heydavid713** [comment]
I tried to change it, my changes worked, but they are not compatible with 5.1 :(

**Comment by AzeemMichael** [comment]
@heydavid713 I was wondering about that. So, would this be pushed for v2.0? I do, however, see some bug fixes and new features in 2.0 that I'm sure 1.2 community would want.

**Comment by heydavid713** [comment]
@AzreemMichael Since a major version change is needed, 2.0 should target Laravel 5.2 onwards and keep 1.2 as LTS since Laravel 5.1 is LTS too.

**Comment by bramdevries** [comment]
Is there any update on when 2.0 will be released?

**Comment by mormy** [comment]
What is the status for 2.0, i see it's in alpha, when will it be ready?

**Comment by Mulkave** [comment]
@mormy @bramdevries 2.0 should be out by end of next week :)

**Comment by mormy** [comment]
Awesome dude! 

If I can help somehow (even testing, which I hate), just give me a holler!

**Comment by Mulkave** [comment]
@mormy cool! Thanks a lot. Will ping this issue once a ready version of it is out.

**Comment by Sekonda** [comment]
Any news on this?

**Comment by Sekonda** [comment]
Any news on this @Mulkave ?

**Comment by Mulkave** [comment]
@Sekonda unfortunately no :disappointed: it's taking a bit longer. Will provide a more accurate ETA in two days from now. Sorry.

**Comment by poem** [comment]
@Mulkave Really looking forward to 2.0 :smile:

**Comment by jeroenherczeg** [comment]
```composer require vinelab/neoeloquent
Using version ^1.3 for vinelab/neoeloquent
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for vinelab/neoeloquent ^1.3 -> satisfiable by vinelab/neoeloquent[v1.3.0].
    - Conclusion: remove laravel/framework v5.2.11
    - Conclusion: don't install laravel/framework v5.2.11
    - vinelab/neoeloquent v1.3.0 requires illuminate/pagination 5.1.* -> satisfiable by illuminate/pagination[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - don't install illuminate/pagination v5.1.1|don't install laravel/framework v5.2.11
    - don't install illuminate/pagination v5.1.13|don't install laravel/framework v5.2.11
    - don't install illuminate/pagination v5.1.16|don't install laravel/framework v5.2.11
    - don't install illuminate/pagination v5.1.2|don't install laravel/framework v5.2.11
    - don't install illuminate/pagination v5.1.20|don't install laravel/framework v5.2.11
    - don't install illuminate/pagination v5.1.22|don't install laravel/framework v5.2.11
    - don't install illuminate/pagination v5.1.25|don't install laravel/framework v5.2.11
    - don't install illuminate/pagination v5.1.28|don't install laravel/framework v5.2.11
    - don't install illuminate/pagination v5.1.30|don't install laravel/framework v5.2.11
    - don't install illuminate/pagination v5.1.31|don't install laravel/framework v5.2.11
    - don't install illuminate/pagination v5.1.6|don't install laravel/framework v5.2.11
    - don't install illuminate/pagination v5.1.8|don't install laravel/framework v5.2.11
    - Installation request for laravel/framework == 5.2.11.0 -> satisfiable by laravel/framework[v5.2.11].


Installation failed, reverting ./composer.json to its original content.```

**Comment by heydavid713** [comment]
I just recently updated our project to Laravel 5.2 and we had no issues. Will do the pull request to 1.3.0. I also fixed an issue with Soft Deletion due to the new global scopes in Laravel 5.2.

**Comment by Mulkave** [comment]
@heydavid713 awesome! Thanks a bunch :smile:

**Comment by heydavid713** [comment]
@jeroenherczeg @Mulkave  Added some composer dependencies to fix that problem.

**Comment by fuzzybaird** [comment]
Did we get this solved for 5.2+? I still get the same error as @jeroenherczeg.

**Comment by Mulkave** [comment]
@fuzzybaird, @heydavid713 resolved this with that PR, please update your composer to get the 1.3 version

**Comment by heydavid713** [comment]
@Mulkave hmm it seems the PR is still open for that fix. But I noticed all the tests failed in the "getDoctrineConnection" method. Is this something you worked on you version of the neo4jphp fork? This is something I noticed in other project I started working on last night. Either way, I'll have a go at merging your version of neo4jphp with mine and see the results from that, but that will probably fix the problem with tests failing.

**Comment by fuzzybaird** [comment]
So the change has not been merged because of the failed tests? So 1.3 still does not work correct? I am sorry I am new to github so the lingo is a little confusing.

**Comment by Mulkave** [comment]
@heydavid713 any updates on the merge for neo4jphp? Yes we've forked and are using our own version of it, though no major changes only compatibility stuff..

**Comment by heydavid713** [comment]
@fuzzybaird I haven't had the time to correct the tests yet. Will try and
do it this week. Even though is like you said, it it just compatibility so
everything should be fine.

**Comment by heydavid713** [comment]
@Mulkave something changed in how getDoctrineDriver was called in Illuminate/Database and I have been trying to figure it out to no avail. However, even if the tests are failing due to that, there was no other change at all. We have ben using 1.3.0 in production for about the same time I opened the PR and we haven't had any problems

**Comment by kvailas** [comment]
Is it possible to make 1.3.0 version of neoeloquent compatible with laravel 5.2.x ?
Its working, so its only a composer.json change and voila.
Just make that commit so that we don't really have to mess with forking etc.

Thank you in advance.

**Comment by KinaneD** [comment]
@kvailas the composer.json file has been updated and pushed. Although tests are failing, due to a change in Laravel, these remains internal and does not affect functionality. @heydavid713 can confirm that it works fine with Laravel 5.2.

**Comment by kvailas** [comment]
Thank you for your quick response.
Much appreciated!

**Comment by kvailas** [comment]
could you also publish it to packagist? :)

**Comment by KinaneD** [comment]
It has ben released as 1.3.1

**Comment by kvailas** [comment]
Sure, i just received it!
One thing that came up is the Call to undefined method Illuminate\Foundation\Application::bindShared()

**Comment by AzeemMichael** [comment]
class ``src/Vinelab/NeoEloquent/MigrationServiceProvider.php`` still contains ``$this->app->bindShared()`` and not ``$this->app->singleton()``

**Comment by kelchm** [comment]
I think the 1.3.1 release was tagged incorrectly.  I've just set the version to 1.3.1.x-dev in my composer.json for now.

**Comment by KinaneD** [comment]
@kelchm  Thank you for pointing this out. It has now been fixed.
